Repository AdmiralLvtzov/CicerosKodakkuAssist, pull requests merged in 2025-03, with the labels that each got.

#1 feat: Add DR TTS method & Add TTS Settings group (Move Original TTS checkbox to TTS Settings group)
  FuturesRewrittenUltimate/Karlin's FRU script (Customized by Cicero) Karlin的绝伊甸脚本 (灵视改装版).cs
Labels: enhancement

#4 [New Feature 新功能] Warnings by time for AOEs from spheres in LR in Phase 2 P2光爆球爆炸时间警告
  FuturesRewrittenUltimate/Karlin's FRU script (Customized by Cicero) Karlin的绝伊甸脚本 (灵视改装版).cs
  Program.cs
Labels: enhancement

#5 [Bug Fix & New Feature Bug修复 & 新功能] Fix for the Grey9 strat in LR in Phase 2, additions for the second half of Phase 4 P2光暴新灰9修复 P4二运新增
  FuturesRewrittenUltimate/Karlin's FRU script (Customized by Cicero) Karlin的绝伊甸脚本 (灵视改装版).cs
Labels: bug, enhancement

#6 [Bug Fix Bug修复] Fix the reverse tank positions while the Y formation in C 修复Y字回返在C点时双T位置反向
  FuturesRewrittenUltimate/Karlin's FRU script (Customized by Cicero) Karlin的绝伊甸脚本 (灵视改装版).cs
Labels: bug

#8 选项标注MMW
  FuturesRewrittenUltimate/Karlin's FRU script (Customized by Cicero) Karlin的绝伊甸脚本 (灵视改装版).cs
Labels: documentation

#10 [Improvements 改善] Better paths for puddles of the Grey 9 strat during LR 光爆灰9法放泥路径细化
  FuturesRewrittenUltimate/Karlin's FRU script (Customized by Cicero) Karlin的绝伊甸脚本 (灵视改装版).cs
Labels: enhancement

#11 [Improvements 改善] (Re-submission/重新提交) Amend the ranges of Drachen Wanderers according to players in the second half of Phase 4 P4二运根据玩家修正龙头爆炸范围
  FuturesRewrittenUltimate/Karlin's FRU script (Customized by Cicero) Karlin的绝伊甸脚本 (灵视改装版).cs
Labels: enhancement

#12 [Bug Fix Bug修复] Fix an incorrect pre-condition of debug output 修复一个应该在开发者模式下出现的内容
  FuturesRewrittenUltimate/Karlin's FRU script (Customized by Cicero) Karlin的绝伊甸脚本 (灵视改装版).cs
Labels: bug
